version: "3.7"

services:

  sscms-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  sscms-core:
    depends_on:
      - sscms-db
    image: "dev"
    expose:
      - "80"
    environment:
      SSCMS_SECURITY_KEY: e2a3d303-ac9b-41ff-9154-930710af0845
      SSCMS_DATABASE_TYPE: PostgreSQL
      SSCMS_DATABASE_USER: postgres
      SSCMS_DATABASE_PASSWORD: password
      SSCMS_DATABASE_NAME: postgres
    restart: always

# docker-compose build
# docker-compose up -d
# docker-compose down

# Browse to: http://localhost/ss-admin/
